genormas:
  build: ./gestaonormas
  environment: 
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  ports:
    - 3003:8080
  links:
    - db
db:
  image: postgres:latest
  expose:
  - 5432
  ports:
    - 5432:5432
  environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=api
    - POSTGRES_DB=postgres
  restart: unless-stopped